# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: true

controller_frequency: 5.0
controller_patience: 12.0


planner_frequency: 2.0 #5.0
planner_patience: 120.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "global_planner/GlobalPlanner" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner


recovery_behavior_enabled: true

recovery_behaviors:
  - name: 'super_conservative_reset1'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'conservative_reset1'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset1'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

super_conservative_reset1:
  reset_distance: 2.0
conservative_reset1:
  reset_distance: 0.26
aggressive_reset1:
  reset_distance: 0.0

